stages:
  - build
  - test
build-job:
  image: "node:lts"
  stage: build
  script:
    - npm ci # install the npm dependencies
    - npm run build # build the application
    
test-job:
  stage: test
  script:
   - echo "This job tests something"